image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      bash -c 'dotnet --version'
    command: |
      bash -c 'dotnet new classlib -n QuickLookFontPreview'

vscode:
  extensions:
    - ms-dotnettools.csharp
    
